import os

LOCATION=r"C:\03_workspace\07_oracle\instantclient_19_8"
os.environ["PATH"]=LOCATION+";"+os.environ["PATH"]

#[DB_TYPE]+[DB_CONNECTOR]://[USERNAME]:[PASSWORD]@[HOST]:[PORT]/[DB_NAME]
SQLALCHEMY_DATABASE_URI=""
SQLALCHEMY_ECHO=False
SQLALCHEMY_TRACK_MODIFICATIONS=False