import os

LOCATION=r"C:\03_workspace\07_oracle\instantclient_19_8"
os.environ["PATH"]=LOCATION+";"+os.environ["PATH"]

#[DB_TYPE]+[DB_CONNECTOR]://[USERNAME]:[PASSWORD]@[HOST]:[PORT]/[DB_NAME]
#SQLALCHEMY_DATABASE_URI=environ.get("oracle://BKOMASTER:BKOMASTER66S#@10.40.62.167:14766/SGIFTOD")
SQLALCHEMY_DATABASE_URI="oracle://BKOMASTER:BKOMASTER66S#@10.40.62.167:14766/SGIFTOD"
SQLALCHEMY_ECHO=False
SQLALCHEMY_TRACK_MODIFICATIONS=False